environment:
  matrix:
    - nodejs_version: '9'
    - nodejs_version: '8'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - set NODE_ENV=development
  - npm install

matrix:
  fast_finish: true

build: off

shallow_clone: false

test_script:
  - node --version
  - npm --version
  - npm test
